//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RksvSign
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RksvSign.IATSSCD")]
    public interface IATSSCD
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATSSCD/Certificate", ReplyAction="http://tempuri.org/IATSSCD/CertificateResponse")]
        System.Threading.Tasks.Task<byte[]> CertificateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATSSCD/ZDA", ReplyAction="http://tempuri.org/IATSSCD/ZDAResponse")]
        System.Threading.Tasks.Task<string> ZDAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATSSCD/Sign", ReplyAction="http://tempuri.org/IATSSCD/SignResponse")]
        System.Threading.Tasks.Task<byte[]> SignAsync(byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATSSCD/Echo", ReplyAction="http://tempuri.org/IATSSCD/EchoResponse")]
        System.Threading.Tasks.Task<string> EchoAsync(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IATSSCDChannel : RksvSign.IATSSCD, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ATSSCDClient : System.ServiceModel.ClientBase<RksvSign.IATSSCD>, RksvSign.IATSSCD
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ATSSCDClient() : 
                base(ATSSCDClient.GetDefaultBinding(), ATSSCDClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CustomBinding_IATSSCD.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ATSSCDClient(EndpointConfiguration endpointConfiguration) : 
                base(ATSSCDClient.GetBindingForEndpoint(endpointConfiguration), ATSSCDClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ATSSCDClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ATSSCDClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ATSSCDClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ATSSCDClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ATSSCDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<byte[]> CertificateAsync()
        {
            return base.Channel.CertificateAsync();
        }
        
        public System.Threading.Tasks.Task<string> ZDAAsync()
        {
            return base.Channel.ZDAAsync();
        }
        
        public System.Threading.Tasks.Task<byte[]> SignAsync(byte[] data)
        {
            return base.Channel.SignAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> EchoAsync(string message)
        {
            return base.Channel.EchoAsync(message);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_IATSSCD))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_IATSSCD))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:37587/rksv");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ATSSCDClient.GetBindingForEndpoint(EndpointConfiguration.CustomBinding_IATSSCD);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ATSSCDClient.GetEndpointAddress(EndpointConfiguration.CustomBinding_IATSSCD);
        }
        
        public enum EndpointConfiguration
        {
            
            CustomBinding_IATSSCD,
        }
    }
}
